### ISSUE TITLE
Latest version from repo doesn't work on either 10.1 or 10.2.z

### ISSUE THREAD

**Issue by Deanosim** [jellyfin/jellyfin-plugin-tvheadend#2]
Like the title says it doesn't seem to work, doesn't show up in the plugins menu after being installed. 
I've looked in the server logs and can't see anything that would be causing it to not work.

**Comment by cvium** [comment]
It works for me. Did you clear the cache?

**Comment by Deanosim** [comment]
Is there a button for that? I'm using the docker image so I'd have thought a restart would have cleared the cache.

**Comment by Deanosim** [comment]
Plus this is a fresh install of the container so I don't know what's going on.

**Comment by cvium** [comment]
Browser cache

**Comment by Deanosim** [comment]
Yeah I cleared the cache even tried other browsers, the Jellyfin log says the Plugin is loaded, it's just not showing up, It's a bit odd.

**Comment by krodelabestiole** [comment]
I can see it on the plugin page, and I can configure it, but I don't have access to any TV functionality.
(I installed an Emby binary)
It doesn't change anything in jellyfin interface appart for an empty "TVHeadEnd Recordings" section.
I know for sure my server is working.

How is it supposed to work ?

**Comment by Deanosim** [comment]
Wait so you installed the Emby version of TVHeadend on Jellyfin? No wonder it isn't working properly for you XD

**Comment by Deanosim** [comment]
Also @krodelabestiole You should have started your own Issue for that since it's a different problem.

**Comment by WillWill56** [comment]
I was also experiencing this problem (plugin not showing up in plugin settings). After some investigation, I found the problem was caused by having multiple versions of the tvheadend plugin in my plugins folder.

The older, broken version of the tvheadend plugin I had installed manually at some point (under `plugins/jellyfin-plugin-tvheadend/`) was being loaded instead of the one installed from the plugin catalog. When installing from the catalog, the plugin version is included in the name of the plugin's subdirectory (e.g. `plugins/jellyfin-plugin-tvheadend_1.0.0/`), potentially causing problems when a plugin update is released e.g. 1.1.0, since if it is not removed, the older version might continue to be loaded instead of the newer one...

**Comment by krodelabestiole** [comment]
@Deanosim since this plugin has not been updated for the last two years, and jellyfin 
is 3 months old, I guess this plugin is technically the very same for emby or jellyfin.
the plus being that I don't have to compile it.
I might mistaken though, but I don't get why at the moment.

I didn't want to create a new issue because my question is just : how is it supposed to work ? Which really fit the subject : it doesn't work. In my sense it only supposes to call for a short answer such as : "it should show a TV section on the front end", or "it should show a new service in the live TV settings"...
That's why I didn't want to create a new issue. Sorry if you think it's off topic.

**Comment by WillWill56** [comment]
@krodelabestiole do you have the plugin set up to connect to a running tvheadend server? This plugin is just meant to be a client for that I believe, so without that the plugin doesn't have much functionality. Or is that the part that's not working for you?

**Comment by krodelabestiole** [comment]
@WillWill56 yes sure, the plugin was setup with a server. The issue I had was indeed the fact I was using the wrong plugin i.e. emby's one. I installed the good one v. 1.0.0.0 from the repository that has recently made itself available, and it seems to work. At least a Live TV section appeared on the front end, to answer my question. I have the channels and the TV guide, I still have an issue playing any stream I will have to debug on my own. Anyway I am now clearly off-topic. Thanks everyone !

**Comment by Deanosim** [comment]
So my problem was fixed by what @WillWill56 said, I just removed the plugin and it's folder upgraded to Jellyfin server 10.2.1 and used the repo in the webgui to install and it started working.
So problem solved, guess something in the 10.2.1 update fixed it ¯\_(ツ)_/¯
